### ISSUE TITLE
monadic ⍸

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#287] opened 2024-12-07 16:45 UTC
```
      ⍸3 3 ⍴ 0 0 1 0 1 1
┌───┬───┬───┬───┐
│1 3│2 2│2 3│3 3│
└───┴───┴───┴───┘
```

```
IM> (april "⍸3 3 ⍴ 0 0 1 0 1 1")
   
(:VAL NIL) Invalid input to monadic ⍸ - all elements of argument must be non-negative integers.
   [Condition of type SIMPLE-ERROR]
; Evaluation aborted on NIL

```

**Comment by phantomics** [comment] 2024-12-11 13:06
Odd, this works for me:

```
(april "⍸3 3 ⍴ 0 0 1 0 1 1")
#(#(1 3) #(2 2) #(2 3) #(3 3))
```

Are you using the latest version of April? Is this what the Quicklisp April is doing?

**Comment by julian3ng** [comment] 2024-12-11 16:28
I'm experiencing the same issue - uninstalling and reinstalling `april` gives me `http://beta.quicklisp.org/archive/april/2024-10-12/april-20241012-git.tgz`.

```
APRIL> (april "⍸1 0 1")

(:VAL NIL) 
; Debugger entered on #<SIMPLE-ERROR "Invalid input to monadic ⍸ - all elements of argument must be non-negative integers." {1005196243}>
```

**Comment by phantomics** [comment] 2024-12-12 12:22
Julian, are you using the April that comes from this repo or the April from Quicklisp? I.e. when you said you reinstalled, April, did you do it using `(ql:quickload 'april)`? If you're using the Quicklisp version the problem should be fixed when it makes its next release. If you're using the latest April from the repo, something strange is going on.

**Comment by julian3ng** [comment] 2024-12-12 18:57
I used `ql:quickload`. Good to know next release will fix it!

**Comment by phantomics** [comment] 2024-12-13 12:11
There are unit tests, [you can see them here](https://github.com/phantomics/april/blob/master/spec.lisp#L630). I've added a test for this case. Generating tests automatically has been a thought of mine, however when you produce code like that algorithmically it's easier to lose track of the volume of stuff being generated and have unexpected flaws crop up. For example, if there was a mistake in the algo that produces a bunch of tests that succeed when they should fail, it could be hard to figure out whether the problem is with tests or the implementation and take a long time to track down the cause.

**Comment by justin2004** [comment] 2024-12-13 19:55
> Generating tests automatically has been a thought of mine

@phantomics , nice. i'm glad it seems like a reasonable thing to do.

mostly what i like about thinking about this it is trying to exhaust the variations that might matter. 
e.g.
heterogenous arrays that begin with a number
vs 
heterogenous arrays that begin with character

if i get some time i'll see if i can generate matrix of variations

**Closed** 2024-12-13 19:56 UTC
